[book]
authors = ["sisiodos"]
language = "en"
src = "doc"
title = "Functional Programming in Java"

[build]
build-dir = "docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/sisiodos/fpinjava"
additional-js = ["ga.js"]
